print("Carlos: ¡Hola! ¿Cómo estás?")
print("Ana: ¡Hola! Estoy bien, gracias. ¿Y tú?")
print("Carlos: Muy bien, gracias. ¿Qué tal el clima por tu zona?")
print("Ana: Está bastante soleado hoy. Perfecto para salir a caminar. ¿Y por ahí?")
print("Carlos: Aquí está un poco nublado, pero se siente agradable.")
print("Ana: Qué bien. A veces, un clima nublado también es agradable.")
print("Carlos: Sí, definitivamente. Oye, ¿has probado algún restaurante nuevo últimamente?")
print("Ana: Sí, de hecho, fui a un lugar italiano nuevo el fin de semana pasado. ¡La comida estaba deliciosa!")
print("Carlos: Suena genial. Tendré que probarlo algún día.")
print("Ana: Definitivamente deberías. Bueno, tengo que irme. ¡Fue bueno hablar contigo!")
print("Carlos: Igualmente. ¡Cuídate y que tengas un buen día!")
print("Ana: Gracias, tú también. ¡Adiós!")
print("Carlos: ¡Adiós!")